export { FavoritesPage } from "./FavoritesPage";
export { HomePage } from "./HomePage";
export { MoviePage } from "./MoviePage";
export { ResetPasswordPage } from "./ResetPasswordPage";
export { SearchPage } from "./SearchPage";
export { SettingsPage } from "./SettingsPage";
export { SignInPage } from "./SignInPage";
export { SignUpPage } from "./SignUpPage";
export { TrendsPage } from "./TrendsPage";
